(function(){
'use strict';
const API='https://www.thesportsdb.com/api/v1/json/123';
const CELTIC_ID='133647';
const SPFL_TOTAL=38;
const state={team:null,fixtures:[],table:[],preview:null,transferNews:[],filter:'all',competition:'all',venue:'all',fixtureLimit:12,source:'api'};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const season=()=>{const d=new Date(),y=d.getFullYear();return d.getMonth()>=6?`${y}-${y+1}`:`${y-1}-${y}`};
const eventDate=e=>{if(!e?.dateEvent)return null;const d=new Date(`${e.dateEvent}T${String(e.strTime||'15:00:00').slice(0,8)}Z`);return Number.isNaN(d.valueOf())?null:d};
const isCompleted=e=>e?.intHomeScore!=null&&e?.intAwayScore!=null;
const isHome=e=>/celtic park|parkhead/i.test(e?.strVenue||'')||String(e?.idHomeTeam||'')===CELTIC_ID||/^celtic$/i.test(e?.strHomeTeam||'');
const isLeague=e=>String(e?.idLeague||'')===String(state.team?.idLeague||'4330')||/scottish premiership|scottish premier league|spfl premiership/i.test(e?.strLeague||'');
const fmtDate=e=>{const d=eventDate(e);if(!d)return{date:'TBC',time:'TBC'};return{date:new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',day:'2-digit',month:'short',year:'numeric'}).format(d),time:new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(d)}};
const fullDate=e=>{const d=eventDate(e);return d?new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(d):'TBC'};
async function get(path){const c=new AbortController(),timer=setTimeout(()=>c.abort(),14000);try{const r=await fetch(`${API}/${path}`,{signal:c.signal});if(!r.ok)throw new Error(`API ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
async function getStatic(){const r=await fetch(`data.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('Static data unavailable');return r.json()}
function empty(text,cols=1){return `<tr><td colspan="${cols}"><div class="empty">${esc(text)}</div></td></tr>`}
function normaliseEvents(items){const map=new Map();for(const e of items||[]){if(!e)continue;map.set(e.idEvent||`${e.dateEvent}-${e.strHomeTeam}-${e.strAwayTeam}`,e)}return [...map.values()].sort((a,b)=>(eventDate(a)?.valueOf()||0)-(eventDate(b)?.valueOf()||0))}
function nextEvent(){const now=Date.now()-10800000;return state.fixtures.find(e=>!isCompleted(e)&&(eventDate(e)?.valueOf()||0)>=now)||state.fixtures.find(e=>!isCompleted(e))||null}
function renderTeam(){const t=state.team||{};$('club-badge').src=t.strBadge||'';$('club-badge').style.visibility=t.strBadge?'visible':'hidden';$('club-name').textContent=t.strTeam||'Celtic FC';$('club-meta').textContent=`${t.strStadium||'Celtic Park'} · Founded ${t.intFormedYear||'1888'}`;$('club-league').textContent=t.strLeague||'Scottish Premiership'}
function fixtureRow(e){const dt=fmtDate(e),completed=isCompleted(e),home=isHome(e),score=completed?`${esc(e.intHomeScore)}–${esc(e.intAwayScore)}`:'vs';return `<tr class="${home?'home-match':''}"><td class="date-cell"><strong>${esc(dt.date)}</strong><span>${esc(dt.time)}</span></td><td class="competition-cell"><strong>${esc(e.strLeague||'Competition TBC')}</strong><span>${e.intRound?`Round ${esc(e.intRound)}`:'Season fixture'}</span></td><td><div class="fixture-cell"><strong class="home">${esc(e.strHomeTeam||'TBC')}</strong><b class="score">${score}</b><strong>${esc(e.strAwayTeam||'TBC')}</strong></div></td><td class="venue-cell"><strong>${esc(e.strVenue||'Venue TBC')}</strong>${home?'<span class="venue-chip">Celtic Park</span>':''}</td><td><span class="status-chip ${completed?'complete':'upcoming'}">${completed?'FT':'Scheduled'}</span></td></tr>`}
function resultRow(e){const dt=fmtDate(e);return `<article class="result-row ${isHome(e)?'home-result':''}"><div class="result-date">${esc(dt.date.replace(/\s\d{4}$/,''))}</div><div class="result-fixture"><strong>${esc(e.strHomeTeam)} v ${esc(e.strAwayTeam)}</strong><span>${esc(e.strLeague||'Competition')}</span></div><div class="result-score">${esc(e.intHomeScore)}–${esc(e.intAwayScore)}</div></article>`}
function renderFixtures(){const now=Date.now();let items=[...state.fixtures];if(state.filter==='upcoming')items=items.filter(e=>!isCompleted(e)&&(eventDate(e)?.valueOf()||0)>=now-86400000);if(state.filter==='completed')items=items.filter(isCompleted).reverse();if(state.competition!=='all')items=items.filter(e=>(e.strLeague||'')===state.competition);if(state.venue==='home')items=items.filter(isHome);if(state.venue==='away')items=items.filter(e=>!isHome(e));const shown=items.slice(0,state.fixtureLimit);$('fixtures-grid').innerHTML=shown.length?shown.map(fixtureRow).join(''):empty('No fixtures match the selected filters.',5);$('fixture-count').textContent=`${shown.length} of ${items.length} shown`;$('show-more').classList.toggle('hidden',shown.length>=items.length);const leagueCount=state.fixtures.filter(isLeague).length;$('fixture-summary').textContent=`${leagueCount}/${SPFL_TOTAL}`;$('matches-summary').textContent=String(state.fixtures.length);$('coverage-value').textContent=`${leagueCount}/${SPFL_TOTAL}`;$('coverage-progress').style.width=`${Math.min(100,(leagueCount/SPFL_TOTAL)*100)}%`;$('coverage-note').textContent=leagueCount===SPFL_TOTAL?'The full league programme is published.':`${SPFL_TOTAL-leagueCount} post-split league fixtures remain to be published.`;const coverage=leagueCount===SPFL_TOTAL?'The full 38-match Scottish Premiership programme is published.':`${leagueCount} of 38 Scottish Premiership fixtures are currently published.`;$('fixture-note').textContent=`${coverage} ${state.fixtures.length} matches are listed across all competitions.`;const completed=state.fixtures.filter(isCompleted).sort((a,b)=>(eventDate(b)?.valueOf()||0)-(eventDate(a)?.valueOf()||0)).slice(0,5);$('results-grid').innerHTML=completed.length?completed.map(resultRow).join(''):'<div class="empty">No completed matches available.</div>';const n=nextEvent();$('next-summary').textContent=n?`${n.strHomeTeam} v ${n.strAwayTeam}`:'TBC';$('next-date-summary').textContent=n?fullDate(n):'Awaiting schedule'}
function setFixtureFilters(){const competitions=[...new Set(state.fixtures.map(e=>e.strLeague).filter(Boolean))].sort();$('competition-filter').innerHTML='<option value="all">All competitions</option>'+competitions.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function formHtml(value){return String(value||'').split('').slice(-5).map(x=>`<span class="${x.toLowerCase()}">${esc(x)}</span>`).join('')}
function teamPosition(id,name){const row=state.table.find(r=>String(r.idTeam||'')===String(id)||String(r.name||r.strTeam||'').toLowerCase()===String(name||'').toLowerCase());return row?(row.intRank||row.intPosition||'–'):'–'}
function renderTable(){const rows=state.table;if(!rows.length){$('table-content').innerHTML='<div class="empty">The current league table is unavailable.</div>';$('position-summary').textContent='—';return}const celtic=rows.find(r=>/celtic/i.test(r.name||r.strTeam||''));$('position-summary').textContent=celtic?`#${celtic.intRank||celtic.intPosition||'–'}`:'—';$('table-content').innerHTML=`<div class="table-wrap"><table class="league-table"><thead><tr><th>#</th><th>Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GD</th><th>Pts</th><th>Form</th></tr></thead><tbody>${rows.map(r=>{const name=r.name||r.strTeam||'';return `<tr class="${/celtic/i.test(name)?'celtic':''}"><td class="pos">${esc(r.intRank||r.intPosition||'')}</td><td><strong>${esc(name)}</strong></td><td>${esc(r.intPlayed||'')}</td><td>${esc(r.intWin||'')}</td><td>${esc(r.intDraw||'')}</td><td>${esc(r.intLoss||'')}</td><td>${esc(r.intGoalDifference||'')}</td><td><strong>${esc(r.intPoints||'')}</strong></td><td><span class="form">${formHtml(r.strForm)}</span></td></tr>`}).join('')}</tbody></table></div>`}
function newsDate(value){const d=new Date(value);return Number.isNaN(d.valueOf())?'Recent':new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',day:'numeric',month:'short',year:'numeric'}).format(d)}
function renderTransfers(){const items=(state.transferNews||[]).slice(0,9);$('transfer-grid').innerHTML=items.length?items.map(item=>`<article class="news-item"><div class="news-meta"><span class="news-label ${esc((item.kind||'report').toLowerCase())}">${esc(item.kind||'Report')}</span><time>${esc(newsDate(item.publishedAt))}</time></div><h3>${esc(item.title||'Celtic transfer update')}</h3>${item.summary?`<p>${esc(item.summary)}</p>`:''}<a href="${esc(item.url||'#')}" target="_blank" rel="noreferrer">${esc(item.source||'Original source')} ↗</a></article>`).join(''):'<div class="empty">No approved transfer reports are available.</div>'}
function latestResultText(items){const e=(items||[]).find(isCompleted)||(items||[])[0];return e&&e.intHomeScore!=null?`${e.strHomeTeam} ${e.intHomeScore}–${e.intAwayScore} ${e.strAwayTeam}`:'Not available'}
async function buildPreview(){const event=nextEvent();if(!event){$('preview-content').innerHTML='<div class="empty">The next match has not been published yet.</div>';return}let home=state.preview?.homeTeam||null,away=state.preview?.awayTeam||null,homeRecent=state.preview?.homeRecent||[],awayRecent=state.preview?.awayRecent||[];try{const calls=await Promise.allSettled([home?Promise.resolve({teams:[home]}):get(`lookupteam.php?id=${event.idHomeTeam}`),away?Promise.resolve({teams:[away]}):get(`lookupteam.php?id=${event.idAwayTeam}`),homeRecent.length?Promise.resolve({results:homeRecent}):get(`eventslast.php?id=${event.idHomeTeam}`),awayRecent.length?Promise.resolve({results:awayRecent}):get(`eventslast.php?id=${event.idAwayTeam}`)]);home=home||(calls[0].status==='fulfilled'?(calls[0].value.teams||[])[0]:null);away=away||(calls[1].status==='fulfilled'?(calls[1].value.teams||[])[0]:null);homeRecent=homeRecent.length?homeRecent:(calls[2].status==='fulfilled'?(calls[2].value.results||[]):[]);awayRecent=awayRecent.length?awayRecent:(calls[3].status==='fulfilled'?(calls[3].value.results||[]):[])}catch(_){}const h2h=state.fixtures.filter(e=>isCompleted(e)&&((e.idHomeTeam===event.idHomeTeam&&e.idAwayTeam===event.idAwayTeam)||(e.idHomeTeam===event.idAwayTeam&&e.idAwayTeam===event.idHomeTeam))).sort((a,b)=>(eventDate(b)?.valueOf()||0)-(eventDate(a)?.valueOf()||0))[0];$('preview-content').innerHTML=`<article class="preview"><div class="preview-top"><span>${esc(event.strLeague||'Competition TBC')}</span><strong>${esc(fullDate(event))}</strong><span>${esc(event.strVenue||'Venue TBC')}</span></div><div class="preview-teams"><div class="preview-team"><img src="${esc(home?.strBadge||event.strHomeTeamBadge||'')}" alt=""><div><h3>${esc(event.strHomeTeam||home?.strTeam||'Home')}</h3><p>League position: ${esc(teamPosition(event.idHomeTeam,event.strHomeTeam))}</p></div></div><div class="preview-vs">VS</div><div class="preview-team"><img src="${esc(away?.strBadge||event.strAwayTeamBadge||'')}" alt=""><div><h3>${esc(event.strAwayTeam||away?.strTeam||'Away')}</h3><p>League position: ${esc(teamPosition(event.idAwayTeam,event.strAwayTeam))}</p></div></div></div><div class="preview-facts"><div class="preview-fact"><span>Home latest</span><strong>${esc(latestResultText(homeRecent))}</strong></div><div class="preview-fact"><span>Away latest</span><strong>${esc(latestResultText(awayRecent))}</strong></div><div class="preview-fact"><span>Last meeting</span><strong>${esc(h2h?`${h2h.strHomeTeam} ${h2h.intHomeScore}–${h2h.intAwayScore} ${h2h.strAwayTeam}`:'Not in current data')}</strong></div><div class="preview-fact"><span>Location</span><strong>${esc(isHome(event)?'Celtic Park':event.strVenue||'TBC')}</strong></div></div><div class="preview-note">Facts reflect the latest records returned by TheSportsDB and are informational rather than predictive.</div></article>`}
function notice(text){$('status').textContent=text;$('status').classList.add('show')}
async function loadFallback(){const [teamR,nextR,prevR,tableR,seasonR]=await Promise.allSettled([get(`lookupteam.php?id=${CELTIC_ID}`),get(`eventsnext.php?id=${CELTIC_ID}`),get(`eventslast.php?id=${CELTIC_ID}`),get(`lookuptable.php?l=4330&s=${season()}`),get(`eventsseason.php?id=4330&s=${season()}`)]);state.team=teamR.status==='fulfilled'?(teamR.value.teams||[])[0]:null;const leagueEvents=seasonR.status==='fulfilled'?(seasonR.value.events||[]):[];const all=[...leagueEvents,...(nextR.status==='fulfilled'?(nextR.value.events||[]):[]),...(prevR.status==='fulfilled'?(prevR.value.results||[]):[])].filter(e=>String(e.idHomeTeam||'')===CELTIC_ID||String(e.idAwayTeam||'')===CELTIC_ID||/celtic/i.test(`${e.strHomeTeam} ${e.strAwayTeam}`));state.fixtures=normaliseEvents(all);state.table=tableR.status==='fulfilled'?(tableR.value.table||[]):[];state.source='api';notice('Expanded season data is refreshing. Showing the live API fallback.')}
async function load(){const btn=$('refresh');btn.disabled=true;btn.textContent='Refreshing…';$('status').classList.remove('show');try{try{const data=await getStatic();state.transferNews=data.transferNews||[];state.team=data.team||null;state.fixtures=normaliseEvents(data.fixtures||[]);state.table=data.table||[];state.preview=data.preview||null;state.source='generated';if(!state.team||!state.fixtures.length)throw new Error('Generated data incomplete');const stamp=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',dateStyle:'medium',timeStyle:'short'}).format(new Date(data.generatedAt));$('updated').textContent=stamp;$('freshness-summary').textContent='Current'}catch(_){await loadFallback();const stamp=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',dateStyle:'medium',timeStyle:'short'}).format(new Date());$('updated').textContent=stamp;$('freshness-summary').textContent='API fallback'}renderTeam();setFixtureFilters();renderFixtures();renderTransfers();renderTable();$('season-label').textContent=`Season ${season()} · 38 league matches per club`;await buildPreview()}catch(err){notice('Celtic data is temporarily unavailable. Please refresh shortly.');$('fixtures-grid').innerHTML=empty('Fixtures unavailable.',5);$('results-grid').innerHTML='<div class="empty">Results unavailable.</div>';$('table-content').innerHTML='<div class="empty">League table unavailable.</div>';$('preview-content').innerHTML='<div class="empty">Match preview unavailable.</div>';renderTransfers()}finally{btn.disabled=false;btn.textContent='Refresh data'}}
$('menu').addEventListener('click',()=>{const open=$('links').classList.toggle('open');$('menu').setAttribute('aria-expanded',String(open))});
$('refresh').addEventListener('click',load);
$('fixture-tools').addEventListener('click',e=>{const button=e.target.closest('button[data-filter]');if(!button)return;state.filter=button.dataset.filter;state.fixtureLimit=12;document.querySelectorAll('#fixture-tools button[data-filter]').forEach(b=>b.classList.toggle('active',b===button));renderFixtures()});
$('competition-filter').addEventListener('change',e=>{state.competition=e.target.value;state.fixtureLimit=12;renderFixtures()});
$('venue-filter').addEventListener('change',e=>{state.venue=e.target.value;state.fixtureLimit=12;renderFixtures()});
$('show-more').addEventListener('click',()=>{state.fixtureLimit+=12;renderFixtures()});
load();
})();