(function(){
'use strict';
const API='https://www.thesportsdb.com/api/v1/json/123';
const CELTIC_ID='133647';
const SPFL_TOTAL=38;
const state={team:null,fixtures:[],players:[],table:[],preview:null,transferNews:[],filter:'all',source:'api'};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const season=()=>{const d=new Date(),y=d.getFullYear();return d.getMonth()>=6?`${y}-${y+1}`:`${y-1}-${y}`};
const eventDate=e=>{if(!e?.dateEvent)return null;const raw=`${e.dateEvent}T${String(e.strTime||'15:00:00').slice(0,8)}Z`;const d=new Date(raw);return Number.isNaN(d.valueOf())?new Date(`${e.dateEvent}T12:00:00Z`):d};
const isCompleted=e=>e?.intHomeScore!=null&&e?.intAwayScore!=null;
const isCelticPark=e=>/celtic park|parkhead/i.test(e?.strVenue||'')||String(e?.idHomeTeam||'')===CELTIC_ID||/^celtic$/i.test(e?.strHomeTeam||'');
const isLeague=e=>String(e?.idLeague||'')===String(state.team?.idLeague||'4330')||/scottish premiership|spfl premiership/i.test(e?.strLeague||'');
const dateText=e=>{const d=eventDate(e);return d?new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(d):'TBC'};
async function get(path){const c=new AbortController(),timer=setTimeout(()=>c.abort(),14000);try{const r=await fetch(`${API}/${path}`,{signal:c.signal});if(!r.ok)throw new Error(`API ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
async function getStatic(){const r=await fetch(`data.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('Static data unavailable');return r.json()}
function empty(text){return `<div class="empty">${esc(text)}</div>`}
function matchCard(e){const completed=isCompleted(e),score=completed?`${esc(e.intHomeScore)} – ${esc(e.intAwayScore)}`:'vs',home=isCelticPark(e);return `<article class="match ${home?'home-match':''}"><div class="match-meta"><span>${esc(e.strLeague||'Competition TBC')}</span><span>${esc(dateText(e))}</span></div><div class="teams"><strong>${esc(e.strHomeTeam||'TBC')}</strong><b class="score">${score}</b><strong>${esc(e.strAwayTeam||'TBC')}</strong></div><div class="venue-row"><p class="venue">${esc(e.strVenue||'Venue TBC')}</p>${home?'<span class="chip home">Celtic Park</span>':''}</div></article>`}
function normaliseEvents(items){const map=new Map();for(const e of items||[]){if(!e)continue;const key=e.idEvent||`${e.dateEvent}-${e.strHomeTeam}-${e.strAwayTeam}`;map.set(key,e)}return [...map.values()].sort((a,b)=>(eventDate(a)?.valueOf()||0)-(eventDate(b)?.valueOf()||0))}
function nextEvent(){const now=Date.now()-10800000;return state.fixtures.find(e=>!isCompleted(e)&&(eventDate(e)?.valueOf()||0)>=now)||state.fixtures.find(e=>!isCompleted(e))||null}
function renderTeam(){const t=state.team||{};$('club-badge').src=t.strBadge||'';$('club-badge').style.visibility=t.strBadge?'visible':'hidden';$('club-name').textContent=t.strTeam||'Celtic FC';$('club-meta').textContent=`${t.strStadium||'Celtic Park'} · Founded ${t.intFormedYear||'1888'}`;$('club-league').textContent=t.strLeague||'Scottish Premiership'}
function renderFixtures(){const now=Date.now();let items=state.fixtures;if(state.filter==='upcoming')items=items.filter(e=>!isCompleted(e)&&(eventDate(e)?.valueOf()||0)>=now-86400000);if(state.filter==='completed')items=items.filter(isCompleted).reverse();$('fixtures-grid').innerHTML=items.length?items.map(matchCard).join(''):empty('No fixtures match this view.');const leagueCount=state.fixtures.filter(isLeague).length;$('fixture-count').textContent=`${items.length} shown · ${state.fixtures.length} all competitions`;$('fixture-summary').textContent=`${leagueCount}/${SPFL_TOTAL} published`;const n=nextEvent();$('next-summary').textContent=n?`${n.strHomeTeam} v ${n.strAwayTeam}`:'TBC';const completed=state.fixtures.filter(isCompleted).sort((a,b)=>(eventDate(b)?.valueOf()||0)-(eventDate(a)?.valueOf()||0)).slice(0,6);$('results-grid').innerHTML=completed.length?completed.map(matchCard).join(''):empty('No completed matches are available yet.');const coverage=leagueCount===SPFL_TOTAL?'The full 38-match Scottish Premiership programme is published.':`${leagueCount} of 38 Scottish Premiership matches are currently published; post-split fixtures are added when released.`;$('fixture-note').textContent=`${coverage} ${state.fixtures.length} matches are listed across all competitions.`}
function renderPlayers(){const query=$('player-search').value.trim().toLowerCase(),position=$('position-filter').value;const items=state.players.filter(p=>(!query||`${p.strPlayer||''} ${p.strPosition||''}`.toLowerCase().includes(query))&&(!position||p.strPosition===position));$('squad-grid').innerHTML=items.length?items.map(p=>{const image=p.strCutout||p.strThumb,initials=(p.strPlayer||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2);return `<article class="player"><div class="player-photo">${image?`<img loading="lazy" src="${esc(image)}" alt="${esc(p.strPlayer||'Celtic player')}">`:`<span class="initials">${esc(initials)}</span>`}</div><div class="player-body"><h3>${esc(p.strPlayer||'Unknown player')}</h3><p>${esc(p.strPosition||'Player')}</p><small>${esc(p.strNationality||'')}</small></div></article>`}).join(''):empty('No players match the current filter.');$('squad-summary').textContent=`${state.players.length} players`;$('squad-count').textContent=`Showing ${items.length} of ${state.players.length} squad players`}
function setPlayerFilters(){const positions=[...new Set(state.players.map(p=>p.strPosition).filter(Boolean))].sort();$('position-filter').innerHTML='<option value="">All positions</option>'+positions.map(x=>`<option>${esc(x)}</option>`).join('')}
function formHtml(value){return String(value||'').split('').slice(-5).map(x=>`<span class="${x.toLowerCase()}">${esc(x)}</span>`).join('')}
function teamPosition(id,name){const row=state.table.find(r=>String(r.idTeam||'')===String(id)||String(r.name||r.strTeam||'').toLowerCase()===String(name||'').toLowerCase());return row?(row.intRank||row.intPosition||'–'):'–'}
function renderTable(){const rows=state.table;if(!rows.length){$('table-content').innerHTML=empty('The current league table was not available from the API.');$('position-summary').textContent='Unavailable';return}const celtic=rows.find(r=>/celtic/i.test(r.name||r.strTeam||''));$('position-summary').textContent=celtic?`${celtic.intRank||celtic.intPosition||'–'}`:'Unavailable';$('table-content').innerHTML=`<div class="table-wrap"><table class="league-table"><thead><tr><th>#</th><th>Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GD</th><th>Pts</th><th>Form</th></tr></thead><tbody>${rows.map(r=>{const name=r.name||r.strTeam||'';return `<tr class="${/celtic/i.test(name)?'celtic':''}"><td class="pos">${esc(r.intRank||r.intPosition||'')}</td><td><strong>${esc(name)}</strong></td><td>${esc(r.intPlayed||'')}</td><td>${esc(r.intWin||'')}</td><td>${esc(r.intDraw||'')}</td><td>${esc(r.intLoss||'')}</td><td>${esc(r.intGoalDifference||'')}</td><td><strong>${esc(r.intPoints||'')}</strong></td><td><span class="form">${formHtml(r.strForm)}</span></td></tr>`}).join('')}</tbody></table></div>`}
function newsDate(value){const d=new Date(value);return Number.isNaN(d.valueOf())?'Recent':new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',day:'numeric',month:'short',year:'numeric'}).format(d)}
function renderTransfers(){const items=(state.transferNews||[]).slice(0,9);$('transfer-grid').innerHTML=items.length?items.map(item=>`<article class="news-card"><div class="news-meta"><span class="news-label ${esc((item.kind||'report').toLowerCase())}">${esc(item.kind||'Report')}</span><span>${esc(newsDate(item.publishedAt))}</span></div><h3>${esc(item.title||'Celtic transfer update')}</h3>${item.summary?`<p>${esc(item.summary)}</p>`:''}<a href="${esc(item.url||'#')}" target="_blank" rel="noreferrer">${esc(item.source||'Original source')} ↗</a></article>`).join(''):empty('No recent transfer reports from the approved source list are available.')}
function latestResultText(items){const e=(items||[]).find(isCompleted)||(items||[])[0];return e&&e.intHomeScore!=null?`${e.strHomeTeam} ${e.intHomeScore}–${e.intAwayScore} ${e.strAwayTeam}`:'Not available'}
async function buildPreview(){const event=nextEvent();if(!event){$('preview-content').innerHTML=empty('The next match has not been published yet.');return}let home=state.preview?.homeTeam||null,away=state.preview?.awayTeam||null,homeRecent=state.preview?.homeRecent||[],awayRecent=state.preview?.awayRecent||[];try{const calls=await Promise.allSettled([home?Promise.resolve({teams:[home]}):get(`lookupteam.php?id=${event.idHomeTeam}`),away?Promise.resolve({teams:[away]}):get(`lookupteam.php?id=${event.idAwayTeam}`),homeRecent.length?Promise.resolve({results:homeRecent}):get(`eventslast.php?id=${event.idHomeTeam}`),awayRecent.length?Promise.resolve({results:awayRecent}):get(`eventslast.php?id=${event.idAwayTeam}`)]);home=home||(calls[0].status==='fulfilled'?(calls[0].value.teams||[])[0]:null);away=away||(calls[1].status==='fulfilled'?(calls[1].value.teams||[])[0]:null);homeRecent=homeRecent.length?homeRecent:(calls[2].status==='fulfilled'?(calls[2].value.results||[]):[]);awayRecent=awayRecent.length?awayRecent:(calls[3].status==='fulfilled'?(calls[3].value.results||[]):[])}catch(_){}
const h2h=state.fixtures.filter(e=>isCompleted(e)&&((e.idHomeTeam===event.idHomeTeam&&e.idAwayTeam===event.idAwayTeam)||(e.idHomeTeam===event.idAwayTeam&&e.idAwayTeam===event.idHomeTeam))).sort((a,b)=>(eventDate(b)?.valueOf()||0)-(eventDate(a)?.valueOf()||0))[0];const atHome=isCelticPark(event);$('preview-content').innerHTML=`<article class="preview"><div class="preview-top"><span>${esc(event.strLeague||'Competition TBC')}</span><strong>${esc(dateText(event))}</strong><span>${esc(event.strVenue||'Venue TBC')}</span></div><div class="preview-teams"><div class="preview-team"><img src="${esc(home?.strBadge||event.strHomeTeamBadge||'')}" alt=""><h3>${esc(event.strHomeTeam||home?.strTeam||'Home')}</h3><p>League position: ${esc(teamPosition(event.idHomeTeam,event.strHomeTeam))}</p></div><div class="preview-vs">VS</div><div class="preview-team"><img src="${esc(away?.strBadge||event.strAwayTeamBadge||'')}" alt=""><h3>${esc(event.strAwayTeam||away?.strTeam||'Away')}</h3><p>League position: ${esc(teamPosition(event.idAwayTeam,event.strAwayTeam))}</p></div></div><div class="preview-facts"><div class="preview-fact"><span>Home latest</span><strong>${esc(latestResultText(homeRecent))}</strong></div><div class="preview-fact"><span>Away latest</span><strong>${esc(latestResultText(awayRecent))}</strong></div><div class="preview-fact"><span>Last meeting</span><strong>${esc(h2h?`${h2h.strHomeTeam} ${h2h.intHomeScore}–${h2h.intAwayScore} ${h2h.strAwayTeam}`:'Not in current data')}</strong></div><div class="preview-fact"><span>Venue</span><strong>${esc(atHome?'Celtic Park':event.strVenue||'TBC')}</strong></div></div><div class="preview-note">Preview facts reflect the latest records returned by TheSportsDB; they are informational rather than predictive.</div></article>`}
function notice(text){$('status').textContent=text;$('status').classList.add('show')}
async function loadFallback(){const [teamR,nextR,prevR,playersR,tableR,seasonR]=await Promise.allSettled([get(`lookupteam.php?id=${CELTIC_ID}`),get(`eventsnext.php?id=${CELTIC_ID}`),get(`eventslast.php?id=${CELTIC_ID}`),get(`lookup_all_players.php?id=${CELTIC_ID}`),get(`lookuptable.php?l=4330&s=${season()}`),get(`eventsseason.php?id=4330&s=${season()}`)]);state.team=teamR.status==='fulfilled'?(teamR.value.teams||[])[0]:null;const leagueEvents=seasonR.status==='fulfilled'?(seasonR.value.events||[]):[];const all=[...leagueEvents,...(nextR.status==='fulfilled'?(nextR.value.events||[]):[]),...(prevR.status==='fulfilled'?(prevR.value.results||[]):[])].filter(e=>String(e.idHomeTeam||'')===CELTIC_ID||String(e.idAwayTeam||'')===CELTIC_ID||/celtic/i.test(`${e.strHomeTeam} ${e.strAwayTeam}`));state.fixtures=normaliseEvents(all);state.players=playersR.status==='fulfilled'?(playersR.value.player||[]):[];state.table=tableR.status==='fulfilled'?(tableR.value.table||[]):[];state.source='api';notice('The expanded season dataset is refreshing. Showing the live API fallback in the meantime.')}
async function load(){const btn=$('refresh');btn.disabled=true;btn.textContent='Refreshing…';$('status').classList.remove('show');let staticData=null;try{try{staticData=await getStatic();state.transferNews=staticData.transferNews||[];state.team=staticData.team||null;state.fixtures=normaliseEvents(staticData.fixtures||[]);state.players=staticData.players||[];state.table=staticData.table||[];state.preview=staticData.preview||null;state.source='generated';if(!state.team||!state.fixtures.length)throw new Error('Generated data incomplete');$('updated').textContent=`Data refreshed ${new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',dateStyle:'medium',timeStyle:'short'}).format(new Date(staticData.generatedAt))}`}catch(_){await loadFallback();$('updated').textContent=`Live API loaded ${new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',dateStyle:'medium',timeStyle:'short'}).format(new Date())}`}renderTeam();renderFixtures();setPlayerFilters();renderPlayers();renderTransfers();renderTable();$('season-label').textContent=`Season ${season()} · 38 league matches per club`;await buildPreview()}catch(err){notice('Celtic data is temporarily unavailable. Please try refreshing shortly.');$('fixtures-grid').innerHTML=empty('Fixtures unavailable.');$('results-grid').innerHTML=empty('Results unavailable.');$('squad-grid').innerHTML=empty('Squad unavailable.');$('table-content').innerHTML=empty('League table unavailable.');$('preview-content').innerHTML=empty('Match preview unavailable.');renderTransfers()}finally{btn.disabled=false;btn.textContent='Refresh data'}}
$('menu').addEventListener('click',()=>{const open=$('links').classList.toggle('open');$('menu').setAttribute('aria-expanded',String(open))});$('player-search').addEventListener('input',renderPlayers);$('position-filter').addEventListener('change',renderPlayers);$('refresh').addEventListener('click',load);$('fixture-tools').addEventListener('click',e=>{const button=e.target.closest('button[data-filter]');if(!button)return;state.filter=button.dataset.filter;document.querySelectorAll('#fixture-tools button').forEach(b=>b.classList.toggle('active',b===button));renderFixtures()});load();
})();
