(function(){
'use strict';
const ID='133647';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const isEurope=e=>/uefa|champions league|europa league|conference league/i.test(`${e?.strLeague||''} ${e?.strEvent||''}`);
const isCompleted=e=>e?.intHomeScore!=null&&e?.intAwayScore!=null;
const isHome=e=>/celtic park|parkhead/i.test(e?.strVenue||'')||String(e?.idHomeTeam||'')===ID||/^celtic$/i.test(e?.strHomeTeam||'');
const eventDate=e=>{if(!e?.dateEvent)return null;const d=new Date(`${e.dateEvent}T${String(e.strTime||'15:00:00').slice(0,8)}Z`);return Number.isNaN(d.valueOf())?null:d};
const fmt=e=>{const d=eventDate(e);if(!d)return{date:'TBC',time:'TBC',full:'TBC'};return{date:new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',day:'2-digit',month:'short',year:'numeric'}).format(d),time:new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(d),full:new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(d)}};
function row(e){const dt=fmt(e),complete=isCompleted(e),score=complete?`${esc(e.intHomeScore)}–${esc(e.intAwayScore)}`:'vs';return `<tr class="${isHome(e)?'home-match':''}"><td class="date-cell"><strong>${esc(dt.date)}</strong><span>${esc(dt.time)}</span></td><td class="competition-cell"><strong>${esc(e.strLeague||'UEFA')}</strong><span>${e.intRound?`Round ${esc(e.intRound)}`:'European fixture'}</span></td><td><div class="fixture-cell"><strong class="home">${esc(e.strHomeTeam||'TBC')}</strong><b class="score">${score}</b><strong>${esc(e.strAwayTeam||'TBC')}</strong></div></td><td class="venue-cell"><strong>${esc(e.strVenue||'Venue TBC')}</strong>${isHome(e)?'<span class="venue-chip">Celtic Park</span>':''}</td><td><span class="status-chip ${complete?'complete':'upcoming'}">${complete?'FT':'Scheduled'}</span></td></tr>`}
function highlight(e){if(!e)return'<div class="empty">No European fixture has been published yet.</div>';const dt=fmt(e);return `<article class="europe-match"><div class="europe-match-top"><span>${esc(e.strLeague||'UEFA competition')}</span><strong>${esc(dt.full)}</strong></div><div class="europe-teams"><div class="europe-team"><img src="${esc(e.strHomeTeamBadge||'')}" alt=""><h3>${esc(e.strHomeTeam||'Home')}</h3></div><div class="europe-vs">${isCompleted(e)?`${esc(e.intHomeScore)}–${esc(e.intAwayScore)}`:'VS'}</div><div class="europe-team"><img src="${esc(e.strAwayTeamBadge||'')}" alt=""><h3>${esc(e.strAwayTeam||'Away')}</h3></div></div><div class="europe-match-meta"><div><span>Venue</span><strong>${esc(e.strVenue||'TBC')}</strong></div><div><span>Status</span><strong>${isCompleted(e)?'Full time':'Scheduled'}</strong></div></div></article>`}
async function load(){try{const r=await fetch(`data.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('Data unavailable');const data=await r.json(),events=(data.fixtures||[]).filter(isEurope).sort((a,b)=>(eventDate(a)?.valueOf()||0)-(eventDate(b)?.valueOf()||0)),leagues=[...new Set(events.map(e=>e.strLeague).filter(Boolean))],homeCount=events.filter(isHome).length,next=events.find(e=>!isCompleted(e)&&(eventDate(e)?.valueOf()||0)>=Date.now()-10800000)||events.find(e=>!isCompleted(e))||events.at(-1)||null;$('europe-title').textContent=leagues.length===1?leagues[0]:'European campaign';$('europe-competition').textContent=leagues.length===1?leagues[0].replace('UEFA ',''):leagues.length?`${leagues.length} competitions`:'TBC';$('europe-count').textContent=String(events.length);$('europe-home-count').textContent=String(homeCount);$('europe-next').textContent=next?`${next.strHomeTeam} v ${next.strAwayTeam}`:'TBC';$('europe-next-date').textContent=next?fmt(next).full:'Awaiting schedule';$('europe-summary-title').textContent=next&&!isCompleted(next)?'Next European fixture':'Latest European fixture';$('europe-note').textContent=events.length?`${events.length} Celtic matches are published for ${data.season||'the current season'}. Times are shown in London time.`:'No UEFA matches are currently listed for Celtic.';$('europe-highlight').innerHTML=highlight(next);$('europe-grid').innerHTML=events.length?events.map(row).join(''):'<tr><td colspan="5"><div class="empty">Celtic do not currently have Champions League, Europa League or Conference League fixtures in the season dataset.</div></td></tr>'}catch(_){$('europe-grid').innerHTML='<tr><td colspan="5"><div class="empty">European data is refreshing. Please check again shortly.</div></td></tr>';$('europe-highlight').innerHTML='<div class="empty">European campaign data is unavailable.</div>';const s=$('status');s.textContent='The expanded season dataset is not available yet.';s.classList.add('show')}}
$('menu').addEventListener('click',()=>{const open=$('links').classList.toggle('open');$('menu').setAttribute('aria-expanded',String(open))});
load();
})();
